### ISSUE TITLE
Favicon not working on docker

### ISSUE THREAD

**Issue by Djeremaille** [pictuga/morss#41]
Hi,
I can't manage to add a favicon to my morss site. I added favicon.ico in each morss folder to be sure and added this line to index.html header:

`<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" sizes="32x32" />`

I tried other things without success.
When I click the favicon link in the page source I get this:

```
<!-- The above is a description of an error in a Python program, formatted
     for a Web browser because the 'cgitb' module was enabled.  In case you
     are not reading this in a Web browser, here is the original traceback:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/morss/morss.py", line 294, in FeedFetch
    req = crawler.adv_get(url=url, follow=('rss' if not options.items else None), delay=delay, timeout=TIMEOUT * 2)
  File "/usr/lib/python3.8/site-packages/morss/crawler.py", line 68, in adv_get
    con = custom_handler(*args, **kwargs).open(url, timeout=timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1379, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.8/urllib/request.py", line 1319, in do_open
    h = http_class(host, timeout=req.timeout, **http_conn_args)
  File "/usr/lib/python3.8/http/client.py", line 835, in __init__
    self._validate_host(self.host)
  File "/usr/lib/python3.8/http/client.py", line 1208, in _validate_host
    raise InvalidURL(f"URL can't contain control characters. {host!r} "
http.client.InvalidURL: URL can't contain control characters. "{% static '" (found at least ' ')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/morss/morss.py", line 639, in cgi_error_handler
    return app(environ, start_response)
  File "/usr/lib/python3.8/site-packages/morss/morss.py", line 533, in app_wrap
    return func(environ, start_response, app)
  File "/usr/lib/python3.8/site-packages/morss/morss.py", line 633, in cgi_dispatcher
    return app(environ, start_response)
  File "/usr/lib/python3.8/site-packages/morss/morss.py", line 533, in app_wrap
    return func(environ, start_response, app)
  File "/usr/lib/python3.8/site-packages/morss/morss.py", line 583, in cgi_file_handler
    return app(environ, start_response)
  File "/usr/lib/python3.8/site-packages/morss/morss.py", line 509, in cgi_app
    url, rss = FeedFetch(url, options)
  File "/usr/lib/python3.8/site-packages/morss/morss.py", line 297, in FeedFetch
    raise MorssException('Error downloading feed')
morss.morss.MorssException: Error downloading feed

-->
```

**Comment by pictuga** [comment]
That's a known issue, the built-in file server only serves a few predefined paths, see: https://git.pictuga.com/pictuga/morss/src/commit/598a2591f10897970d774368611689547a05718c/morss/wsgi.py#L140-L143

I'm currently working on improving the code to serve _any_ file in the www/ folder, but still WIP

**Comment by pictuga** [comment]
A quick fix if you're in a hurry, add this to the `wsgi.py`file, line 140:

```diff
 files = {
     '': 'text/html',
     'index.html': 'text/html',
+    'favicon.ico': 'image/x-icon',
     'sheet.xsl': 'text/xsl'}
```

**Comment by Djeremaille** [comment]
Thanks a lot!
That's working.
I love your app.
