### ISSUE TITLE
AttributeError: module 'morss' has no attribute 'main'

### ISSUE THREAD

**Issue by frhgit** [pictuga/morss#43]
Hello
I tried to install morss on an up to date arch linux.

```
> pip install git+https://git.pictuga.com/pictuga/morss.git@master
Collecting git+https://git.pictuga.com/pictuga/morss.git@master
  Cloning https://git.pictuga.com/pictuga/morss.git (to revision master) to /tmp/pip-req-build-wgrp5hhd
  Running command git clone -q https://git.pictuga.com/pictuga/morss.git /tmp/pip-req-build-wgrp5hhd
Requirement already satisfied (use --upgrade to upgrade): morss==0.0.0 from git+https://git.pictuga.com/pictuga/morss.git@master in /usr/lib/python3.8/site-packages
Requirement already satisfied: lxml in /usr/lib/python3.8/site-packages (from morss==0.0.0) (4.5.2)
Requirement already satisfied: bs4 in /usr/lib/python3.8/site-packages (from morss==0.0.0) (0.0.1)
Requirement already satisfied: python-dateutil in /usr/lib/python3.8/site-packages (from morss==0.0.0) (2.8.1)
Requirement already satisfied: chardet in /usr/lib/python3.8/site-packages (from morss==0.0.0) (3.0.4)
Requirement already satisfied: pymysql in /usr/lib/python3.8/site-packages (from morss==0.0.0) (0.10.0)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3.8/site-packages (from bs4->morss==0.0.0) (4.9.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.8/site-packages (from python-dateutil->morss==0.0.0) (1.15.0)
Requirement already satisfied: soupsieve>1.2 in /usr/lib/python3.8/site-packages (from beautifulsoup4->bs4->morss==0.0.0) (2.0.1)
Building wheels for collected packages: morss
  Building wheel for morss (setup.py) ... done
  Created wheel for morss: filename=morss-0.0.0-py3-none-any.whl size=62552 sha256=6075ad834cfcecdea16f668925aa5f1725db3c1ec27dfd2c67bb740af00426e5
  Stored in directory: /tmp/pip-ephem-wheel-cache-1iodvrzu/wheels/fa/e1/35/7dc2cbdfdaa5b83a83c5ed461628da31febcef62e43ab29823
Successfully built morss
```

but when i try to use it :
```
morss --help
Traceback (most recent call last):
  File "/usr/bin/morss", line 33, in <module>
    sys.exit(load_entry_point('morss==0.0.0', 'console_scripts', 'morss')())
  File "/usr/bin/morss", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 79, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'morss' has no attribute 'main'
```

Can you help me?
Thank you very much

**Comment by pictuga** [comment]
Yet another known issue sitting somewhere on my todo list for a few days already... I'll fix it "soon"

Temporary fix: you can try to run `python -m morss --help`

**Comment by frhgit** [comment]
This is working. Thank you for this very fast answer. 
Sorry I didn't see that it was a known issue.
Regards

**Comment by pictuga** [comment]
It's a "known issue", known to myself only haha, it's not written anywhere

Thank you for raising the issue tho!

**Comment by pictuga** [comment]
Fixed!

**Comment by frhgit** [comment]
Fix is working!
Thank you
