### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by somedevreally** [pictuga/morss#50]
getting this new error, am running in docker, git build
url: www.maketecheasier.com/feed
the problem is with self-host only, works fine with morss.it
```
File "/usr/lib/python3.8/site-packages/morss/wsgi.py", line 196, in cgi_file_handler
    return app(environ, start_response)
  File "/usr/lib/python3.8/site-packages/morss/wsgi.py", line 132, in cgi_app
    url, rss = FeedFetch(url, options)
  File "/usr/lib/python3.8/site-packages/morss/morss.py", line 275, in FeedFetch
    raise MorssException('Error downloading feed')
morss.morss.MorssException: Error downloading feed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/lib/python3.8/site-packages/morss/wsgi.py", line 156, in app_wrap
    return func(environ, start_response, app)
  File "/usr/lib/python3.8/site-packages/morss/wsgi.py", line 266, in cgi_encode
    out = app(environ, start_response)
  File "/usr/lib/python3.8/site-packages/morss/wsgi.py", line 156, in app_wrap
    return func(environ, start_response, app)
  File "/usr/lib/python3.8/site-packages/morss/wsgi.py", line 260, in cgi_error_handler
    log('ERROR: %s' % repr(e), force=True)
TypeError: log() got an unexpected keyword argument 'force'
[2021-01-03 15:29:41 +0000] [8] [ERROR] Error handling request /favicon.ico
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_reques
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/morss/morss.py", line 272, in FeedFetch
    req = crawler.adv_get(url=url, follow=('rss' if not options.items else None), delay=delay, timeout=TIMEOUT * 2)
  File "/usr/lib/python3.8/site-packages/morss/crawler.py", line 92, in adv_get
    con = custom_handler(*args, **kwargs).open(url, timeout=timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1379, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name does not resolve>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/morss/wsgi.py", line 252, in cgi_error_handler
    return app(environ, start_response)
  File "/usr/lib/python3.8/site-packages/morss/wsgi.py", line 156, in app_wrap
    return func(environ, start_response, app)
  File "/usr/lib/python3.8/site-packages/morss/wsgi.py", line 246, in cgi_dispatcher
    return app(environ, start_response)
  File "/usr/lib/python3.8/site-packages/morss/wsgi.py", line 156, in app_wrap
    return func(environ, start_response, app)
  File "/usr/lib/python3.8/site-packages/morss/wsgi.py", line 196, in cgi_file_handler
    return app(environ, start_response)
  File "/usr/lib/python3.8/site-packages/morss/wsgi.py", line 132, in cgi_app
    url, rss = FeedFetch(url, options)
  File "/usr/lib/python3.8/site-packages/morss/morss.py", line 275, in FeedFetch
    raise MorssException('Error downloading feed')
morss.morss.MorssException: Error downloading feed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/lib/python3.8/site-packages/morss/wsgi.py", line 156, in app_wrap
    return func(environ, start_response, app)
  File "/usr/lib/python3.8/site-packages/morss/wsgi.py", line 266, in cgi_encode
    out = app(environ, start_response)
  File "/usr/lib/python3.8/site-packages/morss/wsgi.py", line 156, in app_wrap
    return func(environ, start_response, app)
  File "/usr/lib/python3.8/site-packages/morss/wsgi.py", line 260, in cgi_error_handler
    log('ERROR: %s' % repr(e), force=True)
TypeError: log() got an unexpected keyword argument 'force'
```

**Comment by Djeremaille** [comment]
Same issue for me via docker install.

**Comment by pictuga** [comment]
made some changes in between. closing. pls reopen if not fixed
