### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by blasterspike** [pictuga/morss#7]
@commit: 5c2151ffd6d7921dde550aeee2a33dde5c0b08a7
Running as CLI, you get this error

```
root@jolokia:~/git/morss# python2.7 -m morss http://www.***.it/rss/homepage/rss2.0.xml
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib/python2.7/runpy.py", line 109, in _get_module_details
    return _get_module_details(pkg_main_name)
  File "/usr/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "morss/__init__.py", line 1, in <module>
    from .morss import *
  File "morss/morss.py", line 202
    'R': ':', 'S': 'www.', , 'T': '#', 'U': '$', 'V': '~', 'W': '!',
                           ^
SyntaxError: invalid syntax
```

Massimo

**Comment by pictuga** [comment]
Ah, right, thanks! I'm on holidays right now (without a proper computer). I'll fix it when I get home. To fix it, just remove a coma (",").

This says that I should write test units to avoid such mistakes

**Comment by pictuga** [comment]
Thanks again
