### ISSUE TITLE
Can't find sheet.xsl on serverless

### ISSUE THREAD

**Issue by eahogue** [pictuga/morss#80]
Hello,

I'm trying to use morss in a serverless service. It is getting packaged into a docker container (automatically by serverless) and deployed. Morss is working fine locally (MacOS), but once deployed I am getting errors that seem to indicate that it cannot find the `www/sheet.xsl` file. 

```
[ERROR] OSError
Traceback (most recent call last):
  File "/var/task/serverless_sdk/__init__.py", line 144, in wrapped_handler
    return user_handler(event, context)
  File "/var/task/crawl-articles-cron/crawl-articles-cron.py", line 255, in crawl
    updated_feed_list = spider()
  File "/var/task/crawl-articles-cron/crawl-articles-cron.py", line 93, in __call__
    parsed_feed = self._get_feed(feed_url)
  File "/var/task/crawl-articles-cron/crawl-articles-cron.py", line 146, in _get_feed
    url, rss = morss.FeedFetch(feed_url, options)  # this only grabs the RSS feed
  File "/tmp/sls-py-req/morss/morss.py", line 306, in FeedFetch
    rss = feeds.parse(req['data'], url=url, encoding=req['encoding'])
  File "/tmp/sls-py-req/morss/feeds.py", line 85, in parse
    rulesets = parse_rules().values()
  File "/tmp/sls-py-req/morss/feeds.py", line 68, in parse_rules
    file_raw = open(data_path(rules[section][arg][5:])).read()
  File "/tmp/sls-py-req/morss/util.py", line 51, in data_path
    raise IOError()END 
```

I am invoking morss like so:

```def _get_feed(self, feed_url: str) -> Dict[str, str]:
    options = morss.Options(resolve=True)
    url, rss = morss.FeedFetch(feed_url, options)  
    rss = morss.FeedGather(
        rss, feed_url, options
    )  
    return json.loads(rss.tojson())
```

Any idea what the problem might be? 

Thanks!

**Comment by pictuga** [comment]
Probably has something to do with how serverless installs python package (and how it treats `data_files` when doing so)

**Comment by pictuga** [comment]
Does b138f11771ebcbffdaf49cfb37343a0b83738f79 solve it?

**Comment by pictuga** [comment]
Feel free to reopen if the issue isn't solved
