### ISSUE TITLE
SQLiteCache error when writing cache to disk

### ISSUE THREAD

**Issue by katchy3132** [pictuga/morss#97]
I get an error when I set the SQLite cache to disk. If I leave it as the memory based default everything is fine. 
 

these is the relevant lines from my docker-compose:
```
            - SQLITE_PATH=/tmp/morss.cache
            - CACHE_SIZE=1000
            - CACHE_LIFESPAN=4500
        volumes:
            - ${PWD}/morss.cache:/tmp/morss.cache

```

and this is the error : 
```
morss    | /usr/bin/python3
morss    | run
morss    | + command -v python
morss    | + command -v python3
morss    | + alias 'python=python3'
morss    | + '[' -z run ]
morss    | + '[' run '=' sh ]
morss    | + '[' run '=' bash ]
morss    | + command -v run
morss    | + run
morss    | + gunicorn --bind 0.0.0.0:8000 --preload --access-logfile - morss
morss    | Traceback (most recent call last):
morss    |   File "/usr/bin/gunicorn", line 8, in <module>
morss    |     sys.exit(run())
morss    |   File "/usr/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
morss    |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
morss    |   File "/usr/lib/python3.10/site-packages/gunicorn/app/base.py", line 231, in run
morss    |     super().run()
morss    |   File "/usr/lib/python3.10/site-packages/gunicorn/app/base.py", line 72, in run
morss    |     Arbiter(self).run()
morss    |   File "/usr/lib/python3.10/site-packages/gunicorn/arbiter.py", line 58, in __init__
morss    |     self.setup(app)
morss    |   File "/usr/lib/python3.10/site-packages/gunicorn/arbiter.py", line 118, in setup
morss    |     self.app.wsgi()
morss    |   File "/usr/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
morss    |     self.callable = self.load()
morss    |   File "/usr/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
morss    |     return self.load_wsgiapp()
morss    |   File "/usr/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
morss    |     return util.import_app(self.app_uri)
morss    |   File "/usr/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
morss    |     mod = importlib.import_module(module)
morss    |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
morss    |     return _bootstrap._gcd_import(name[level:], package, level)
morss    |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
morss    |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
morss    |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
morss    |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
morss    |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
morss    |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
morss    |   File "/usr/lib/python3.10/site-packages/morss/__init__.py", line 22, in <module>
morss    |     from .morss import *
morss    |   File "/usr/lib/python3.10/site-packages/morss/morss.py", line 29, in <module>
morss    |     from . import caching, crawler, feeds, readabilite
morss    |   File "/usr/lib/python3.10/site-packages/morss/caching.py", line 194, in <module>
morss    |     default_cache = SQLiteCache(
morss    |   File "/usr/lib/python3.10/site-packages/morss/caching.py", line 62, in __init__
morss    |     self.con = sqlite3.connect(path, detect_types=sqlite3.PARSE_DECLTYPES, check_same_thread=False)
morss    | sqlite3.OperationalError: unable to open database file
morss    | Exception ignored in: <function SQLiteCache.__del__ at 0x7fd37de56290>
morss    | Traceback (most recent call last):
morss    |   File "/usr/lib/python3.10/site-packages/morss/caching.py", line 71, in __del__
morss    |     self.con.close()
morss    | AttributeError: 'SQLiteCache' object has no attribute 'con'

```

**Comment by pictuga** [comment]
Most likely sqlite didn't have the right to read/write the path you pointed it to. Anyway, sqlite & mysql are being removed as they make little sense since redis & diskcache have been introduced
